baseURL = "https://averp.github.io/diarioweb/"
languageCode = "es"
defaultContentLanguage = "es"
title = "Cronos"
theme = "ananke"

[params]
  # vacío => la portada no muestra posts
  mainSections = []

[permalinks]
  diario = "/diario/:slug/"
  notas-filosoficas = "/notas-filosoficas/:slug/"

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
  name = "Semana 1"
  url  = "/semana1/"
  weight = 10

  [[menu.main]]
  name = "Semana 2"
  url  = "/semana2/"
  weight = 11

  [[menu.main]]
  name = "Semana 3"
  url  = "/semana3/"
  weight = 12

[build.sass]
  transpiler = "dartsass"
